language: csharp
solution: Unosquare.RaspberryIO.sln
notifications:
  slack: unolabs:cbusXPH6pBwZ35rVDzi4k4ve
dotnet: 2.0.0
mono: latest
dist: trusty
install:
  - msbuild /t:Restore
script:
  - msbuild /p:Configuration=Release
